return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "lua-language-server",
      "stylua",
      "html-lsp",
      "css-lsp",
      "prettier",
      "gopls",
      "golangci-lint",
      "golangci-lint-langserver",
      "gofumpt",
      "goimports",
      "golines",
      "delve",
      "bash-language-server",
      "yaml-language-server",
      "helm-ls",
      "groovy-language-server",
      "npm-groovy-lint",
      "typescript-language-server",
      "typos",
    },
  },
}
